In [ ]:
# Conditional logic

# Task Pass/Fail Mapping
# create a status matrix where... mark >= 50 -> 1 (pass) or mark < 50 -> 0 (fail)
# to standardize failing grades replace all marks below 40 with a value of 0

In [1]:
import numpy as np

marks = np.array([
    [78, 45, 32, 67],
    [55, 29, 88, 41],
    [92, 36, 48, 25]
])

print(marks)

status = np.where(marks >= 50, 1, 0)
print(status)

standardize_marks = np.where(marks < 40, 0, marks)
print(standardize_marks)

[[78 45 32 67]
 [55 29 88 41]
 [92 36 48 25]]
[[1 0 0 1]
 [1 0 1 0]
 [1 0 0 0]]
[[78 45  0 67]
 [55  0 88 41]
 [92  0 48  0]]


In [3]:
#Performance Scoring
"""
Avg >= 85 : Grade A (score 10)
Avg >= 70 : Grade B (score 8)
Avg >= 50 : Grade C (score 6)
Below 50 : No grade (score 0)
"""

scores = np.where(marks >= 85, 10, np.where(marks >= 70, 8, np.where(marks >= 50, 6, 0)))
print(scores)

[[ 8  0  0  6]
 [ 6  0 10  0]
 [10  0  0  0]]


In [6]:
#Data Integrity

"""
The copy vs view challenge
Create a backup of marks array
modify the original array (e.g. set marks[0,0] = 0)
check if the backup array changed or remained original
"""

backup = marks.copy()
marks[0, 0] = 0

print(marks)
print(backup)

[[ 0 45 32 67]
 [55 29 88 41]
 [92 36 48 25]]
[[78 45 32 67]
 [55 29 88 41]
 [92 36 48 25]]
