Last Exercise On Numpy

In [1]:
"""
A university monitors electricity usage (in units) of 4 hostels over 7 days(mon and sun)
shape = (4,7)
rows = hostel1, hostel2, hostel3, hostel4
coloumn = mon, tue, wed, thur, fri, sat, sun
"""
import numpy as np
elec = np.random.randint(120, 650, size=(4,7))
print(elec)

[[260 507 151 247 449 535 545]
 [233 491 640 242 278 226 412]
 [423 641 603 346 644 377 579]
 [528 607 567 221 574 134 511]]


In [3]:
print(elec.shape)
print(elec.ndim)
print(elec.size)
print(elec.dtype)

(4, 7)
2
