In [4]:
import numpy as np
arr = np.array([1,2,3,4,5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [1]:
#NumPy automatically expands smaller arrays
import numpy as np # type: ignore
arr = np.array([1,2,3,4])
print(arr + 10)

[11 12 13 14]


In [3]:
import numpy as np
arr = np.array([10,20,30])
print(arr[0])
print(arr[-1])

10
30


In [4]:
a = np.array([1,2,3])
b = a.copy()
b[0] = 99
print(a)
print(b)

[1 2 3]
[99  2  3]


basic array operations (vector power)

In [5]:
a = np.array([1,2,3])
b = np.array([4,5,6])

In [6]:
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


In [6]:
mat = np.array([[1,2,3],[4,5,6]])
print(mat)

[[1 2 3]
 [4 5 6]]


Scalar Operations

In [7]:
print(a + 10)
print(a * 2)

[11 12 13]
[2 4 6]


Universal Functions

In [8]:
arr = np.array([1,4,9,16])

print(np.sqrt(arr))
print(np.log(arr))
print(np.exp(arr))
print(np.max(arr))
print(np.min(arr))
print(np.mean(arr))
print(np.sum(arr))
print(np.std(arr))

[1. 2. 3. 4.]
[0.         1.38629436 2.19722458 2.77258872]
[2.71828183e+00 5.45981500e+01 8.10308393e+03 8.88611052e+06]
16
1
7.5
30
5.678908345800274


In [8]:
np.ones(5)

array([1., 1., 1., 1., 1.])

Invalid scenarios...
example 1: trailing dimension mismatch
Shape A - (4,3) ; Shape B - (4)

shape-A      Shape B
1 2 3       1, 2, 3, 4
4 5 6 
7 8 9 
0 0 0 

example 2:Row mismatch
shape a - (2,2) shape b - (3,2)

In [10]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [13]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])