Slicing & Indexing

In [2]:
import numpy as np

sales = np.array([
    [50, 65, 70, 60],   
    [80, 75, 90, 85],   
    [40, 55, 60, 65],   
    [30, 45, 50, 55]    
])

print(sales)

print(sales[0]) #print first row

print(sales[:, 0:2])

print(sales[2][3])

print(sales[0:2, 0:2])


[[50 65 70 60]
 [80 75 90 85]
 [40 55 60 65]
 [30 45 50 55]]
[50 65 70 60]
[[50 65]
 [80 75]
 [40 55]
 [30 45]]
65
[[50 65]
 [80 75]]


Reshaping & Linespace

In [3]:
sales = np.array([
    [120, 150, 170, 160],
    [200, 210, 190, 220],
    [90,  100, 110, 105]
])

flatten = sales.reshape(12)
print(flatten) #flatten

reshape = sales.reshape(2, 6)
print(reshape)

[120 150 170 160 200 210 190 220  90 100 110 105]
[[120 150 170 160 200 210]
 [190 220  90 100 110 105]]


The Random Module

In [7]:
psales = np.array([
    [120, 150, 170, 160],
    [200, 210, 190, 220],
    [90,  100, 110, 105]
])

random = np.random.randint(0, 20)
print(random)

rand_num = np.random.rand(5)
print(rand_num)

14
[0.55014111 0.56052114 0.55957869 0.21789881 0.43660987]
